--- #YAML:1.0
name: DBIx-Admin-BackupRestore
version: 1.05
author:
  - Ron Savage <ron@savage.net.au>
abstract: |-
  Back-up all tables in a db to XML, and restore them
license: artistic
requires:
  Carp: 0
build_requires:
  Test::More: 0
provides:
  DBIx::Admin::BackupRestore:
    file: lib/DBIx/Admin/BackupRestore.pm
    version: 1.05
generated_by: Module::Build version 0.2607
