--- #YAML:1.0
name: DBIx-Admin-BackupRestore
version: 1.09
author:
  - Ron Savage <ron@savage.net.au>
abstract: |-
  Backup all tables in a database to XML, and restore them
license: artistic
requires:
  Carp: 0
  XML::Parser: 0
  XML::Records: 0
  XML::TokeParser: 0
build_requires:
  Test::More: 0
provides:
  DBIx::Admin::BackupRestore:
    file: lib/DBIx/Admin/BackupRestore.pm
    version: 1.09
generated_by: Module::Build version 0.2611
